### ISSUE TITLE
Does homebrew still provide `imgcat`?

### ISSUE THREAD

**Issue by anicholson** [lonnieking/jif#3]
I looked just now, and I don't see it:

```
$ brew search imgcat
No formula found for "imgcat".
==> Searching pull requests...
$
```

**Comment by lonnieking** [comment]
It appears that I might have forgotten to add a step when I created the Readme file.

This is taken from the [imgcat github page](https://github.com/eddieantonio/imgcat)...

```
brew tap eddieantonio/eddieantonio
brew install imgcat
```
